-- MANUAL DEMO RESET SCRIPT: do not place this file in db/migration.
-- Permanently removes all Product Service products AND product types.
-- Recreates exactly 5 types and 10 products: 5 ACTIVE + 5 RETIRED.

DELETE FROM PRODUCT_STATUS_HISTORY;
DELETE FROM PRODUCT_FEE;
DELETE FROM PRODUCT_TERM;
DELETE FROM PRODUCT_RATE;
DELETE FROM PRODUCT;
DELETE FROM PRODUCT_TYPE_MASTER;

INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY)
VALUES ('SAVINGS', 'Savings Account', 'Everyday retail savings account', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY)
VALUES ('CURRENT', 'Current Account', 'Business transaction account', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY)
VALUES ('SALARY', 'Salary Account', 'Salary-linked savings account', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY)
VALUES ('FD', 'Fixed Deposit', 'Fixed-term deposit product', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY)
VALUES ('CREDIT_CARD', 'Credit Card', 'Revolving credit card product', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script');

DECLARE
  l_active_product_id  PRODUCT.PRODUCT_ID%TYPE;
  l_retired_product_id PRODUCT.PRODUCT_ID%TYPE;
BEGIN
  FOR product_type IN (
    SELECT PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME
    FROM PRODUCT_TYPE_MASTER
    ORDER BY PRODUCT_TYPE_CODE
  ) LOOP
    INSERT INTO PRODUCT (
      PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE_CODE, DESCRIPTION,
      MINIMUM_BALANCE, MAXIMUM_BALANCE, CURRENCY, STATUS, VERSION_NO,
      CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY
    ) VALUES (
      PRODUCT_SEQ.NEXTVAL, 'DEMO_' || product_type.PRODUCT_TYPE_CODE || '_ACTIVE',
      product_type.PRODUCT_TYPE_NAME || ' Active', product_type.PRODUCT_TYPE_CODE,
      'Available product shown in the active catalogue.',
      CASE WHEN product_type.PRODUCT_TYPE_CODE = 'CREDIT_CARD' THEN NULL ELSE 1000 END,
      CASE WHEN product_type.PRODUCT_TYPE_CODE = 'CREDIT_CARD' THEN NULL ELSE 1000000 END,
      'INR', 'ACTIVE', 0, SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script'
    ) RETURNING PRODUCT_ID INTO l_active_product_id;

    INSERT INTO PRODUCT (
      PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE_CODE, DESCRIPTION,
      MINIMUM_BALANCE, MAXIMUM_BALANCE, CURRENCY, STATUS, VERSION_NO,
      CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY
    ) VALUES (
      PRODUCT_SEQ.NEXTVAL, 'DEMO_' || product_type.PRODUCT_TYPE_CODE || '_RETIRED',
      product_type.PRODUCT_TYPE_NAME || ' Classic', product_type.PRODUCT_TYPE_CODE,
      'Retired product retained for catalogue history.',
      CASE WHEN product_type.PRODUCT_TYPE_CODE = 'CREDIT_CARD' THEN NULL ELSE 1000 END,
      CASE WHEN product_type.PRODUCT_TYPE_CODE = 'CREDIT_CARD' THEN NULL ELSE 1000000 END,
      'INR', 'RETIRED', 0, SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script'
    ) RETURNING PRODUCT_ID INTO l_retired_product_id;

    FOR product_row IN (SELECT l_active_product_id AS product_id FROM DUAL UNION ALL SELECT l_retired_product_id FROM DUAL) LOOP
      INSERT INTO PRODUCT_RATE (PRODUCT_RATE_ID, PRODUCT_ID, INTEREST_RATE, VERSION_NO, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY)
      VALUES (PRODUCT_RATE_SEQ.NEXTVAL, product_row.product_id, CASE WHEN product_type.PRODUCT_TYPE_CODE = 'CREDIT_CARD' THEN 0 ELSE 6.5 END, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script');

      INSERT INTO PRODUCT_TERM (PRODUCT_TERM_ID, PRODUCT_ID, TENURE_MONTHS, INSTALLMENT_AMOUNT, INSTALLMENT_FREQUENCY, LOCK_IN_PERIOD, MATURITY_INSTRUCTION, PREMATURE_WITHDRAWAL_ALLOWED, VERSION_NO, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY)
      VALUES (PRODUCT_TERM_SEQ.NEXTVAL, product_row.product_id, CASE WHEN product_type.PRODUCT_TYPE_CODE = 'FD' THEN 12 END, NULL, NULL, CASE WHEN product_type.PRODUCT_TYPE_CODE = 'FD' THEN 3 END, CASE WHEN product_type.PRODUCT_TYPE_CODE = 'FD' THEN 'CREDIT_TO_ACCOUNT' END, CASE WHEN product_type.PRODUCT_TYPE_CODE = 'FD' THEN 1 END, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script');

      INSERT INTO PRODUCT_FEE (PRODUCT_FEE_ID, PRODUCT_ID, MONTHLY_MAINTENANCE_FEE, VERSION_NO, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY)
      VALUES (PRODUCT_FEE_SEQ.NEXTVAL, product_row.product_id, CASE WHEN product_type.PRODUCT_TYPE_CODE = 'CREDIT_CARD' THEN 499 ELSE 0 END, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'demo-script', 'demo-script');
    END LOOP;

    INSERT INTO PRODUCT_STATUS_HISTORY (PRODUCT_STATUS_HISTORY_ID, PRODUCT_ID, PREVIOUS_STATUS, NEW_STATUS, CHANGE_REASON, CHANGED_DATE, CHANGED_BY)
    VALUES (PRODUCT_STATUS_HISTORY_SEQ.NEXTVAL, l_retired_product_id, 'ACTIVE', 'RETIRED', 'Demo product retired for catalogue display.', SYSTIMESTAMP, 'demo-script');
  END LOOP;
END;
/

COMMIT;

-- Expected result: 5 ACTIVE products (top section) and 5 RETIRED products (bottom section).
