CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_RATE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_TERM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_FEE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PRODUCT_TYPE_MASTER (
  PRODUCT_TYPE_CODE VARCHAR2(30) PRIMARY KEY,
  PRODUCT_TYPE_NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(500), STATUS VARCHAR2(20) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL, UPDATED_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(100) NOT NULL, UPDATED_BY VARCHAR2(100) NOT NULL
);

CREATE TABLE PRODUCT (
  PRODUCT_ID NUMBER(19) PRIMARY KEY, PRODUCT_CODE VARCHAR2(50) NOT NULL UNIQUE,
  PRODUCT_NAME VARCHAR2(150) NOT NULL, PRODUCT_TYPE_CODE VARCHAR2(30) NOT NULL,
  DESCRIPTION VARCHAR2(500), MINIMUM_BALANCE NUMBER(19,4), MAXIMUM_BALANCE NUMBER(19,4),
  CURRENCY VARCHAR2(3) NOT NULL, STATUS VARCHAR2(20) NOT NULL, VERSION_NO NUMBER(19) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL, UPDATED_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(100) NOT NULL, UPDATED_BY VARCHAR2(100) NOT NULL,
  CONSTRAINT FK_PRODUCT_TYPE FOREIGN KEY (PRODUCT_TYPE_CODE) REFERENCES PRODUCT_TYPE_MASTER(PRODUCT_TYPE_CODE),
  CONSTRAINT CK_PRODUCT_BALANCE CHECK (MINIMUM_BALANCE IS NULL OR MAXIMUM_BALANCE IS NULL OR MINIMUM_BALANCE <= MAXIMUM_BALANCE)
);

CREATE TABLE PRODUCT_RATE (
  PRODUCT_RATE_ID NUMBER(19) PRIMARY KEY, PRODUCT_ID NUMBER(19) NOT NULL UNIQUE,
  INTEREST_RATE NUMBER(8,4) NOT NULL, VERSION_NO NUMBER(19) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL, UPDATED_DATE TIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100) NOT NULL, UPDATED_BY VARCHAR2(100) NOT NULL,
  CONSTRAINT FK_RATE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
  CONSTRAINT CK_INTEREST_RATE CHECK (INTEREST_RATE >= 0)
);

CREATE TABLE PRODUCT_TERM (
  PRODUCT_TERM_ID NUMBER(19) PRIMARY KEY, PRODUCT_ID NUMBER(19) NOT NULL UNIQUE,
  TENURE_MONTHS NUMBER(10), INSTALLMENT_AMOUNT NUMBER(19,4), INSTALLMENT_FREQUENCY VARCHAR2(30),
  LOCK_IN_PERIOD NUMBER(10), MATURITY_INSTRUCTION VARCHAR2(50), PREMATURE_WITHDRAWAL_ALLOWED NUMBER(1), VERSION_NO NUMBER(19) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL, UPDATED_DATE TIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100) NOT NULL, UPDATED_BY VARCHAR2(100) NOT NULL,
  CONSTRAINT FK_TERM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE PRODUCT_FEE (
  PRODUCT_FEE_ID NUMBER(19) PRIMARY KEY, PRODUCT_ID NUMBER(19) NOT NULL UNIQUE,
  MONTHLY_MAINTENANCE_FEE NUMBER(19,4), VERSION_NO NUMBER(19) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL, UPDATED_DATE TIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100) NOT NULL, UPDATED_BY VARCHAR2(100) NOT NULL,
  CONSTRAINT FK_FEE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
  CONSTRAINT CK_MONTHLY_FEE CHECK (MONTHLY_MAINTENANCE_FEE IS NULL OR MONTHLY_MAINTENANCE_FEE >= 0)
);

INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY) VALUES ('FD', 'Fixed Deposit', 'Term deposit', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'system', 'system');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY) VALUES ('RD', 'Recurring Deposit', 'Monthly installment deposit', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'system', 'system');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY) VALUES ('SAVINGS', 'Savings Account', 'Retail savings account', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'system', 'system');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY) VALUES ('CURRENT', 'Current Account', 'Business transaction account', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'system', 'system');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY) VALUES ('SALARY', 'Salary Account', 'Salary-linked savings account', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'system', 'system');
INSERT INTO PRODUCT_TYPE_MASTER (PRODUCT_TYPE_CODE, PRODUCT_TYPE_NAME, DESCRIPTION, STATUS, CREATED_DATE, UPDATED_DATE, CREATED_BY, UPDATED_BY) VALUES ('CREDIT_CARD', 'Credit Card', 'Revolving credit card product', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP, 'system', 'system');
