CREATE SEQUENCE PRODUCT_STATUS_HISTORY_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PRODUCT_STATUS_HISTORY (
  PRODUCT_STATUS_HISTORY_ID NUMBER(19) PRIMARY KEY,
  PRODUCT_ID NUMBER(19) NOT NULL,
  PREVIOUS_STATUS VARCHAR2(20) NOT NULL,
  NEW_STATUS VARCHAR2(20) NOT NULL,
  CHANGE_REASON VARCHAR2(500) NOT NULL,
  CHANGED_DATE TIMESTAMP NOT NULL,
  CHANGED_BY VARCHAR2(100) NOT NULL,
  CONSTRAINT FK_STATUS_HISTORY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);
