UPDATE PRODUCT_TYPE_MASTER
SET CREATED_BY = 'employee'
WHERE CREATED_BY = 'manager';

UPDATE PRODUCT_TYPE_MASTER
SET UPDATED_BY = 'employee'
WHERE UPDATED_BY = 'manager';

UPDATE PRODUCT
SET CREATED_BY = 'employee'
WHERE CREATED_BY = 'manager';

UPDATE PRODUCT
SET UPDATED_BY = 'employee'
WHERE UPDATED_BY = 'manager';

UPDATE PRODUCT_RATE
SET CREATED_BY = 'employee'
WHERE CREATED_BY = 'manager';

UPDATE PRODUCT_RATE
SET UPDATED_BY = 'employee'
WHERE UPDATED_BY = 'manager';

UPDATE PRODUCT_TERM
SET CREATED_BY = 'employee'
WHERE CREATED_BY = 'manager';

UPDATE PRODUCT_TERM
SET UPDATED_BY = 'employee'
WHERE UPDATED_BY = 'manager';

UPDATE PRODUCT_FEE
SET CREATED_BY = 'employee'
WHERE CREATED_BY = 'manager';

UPDATE PRODUCT_FEE
SET UPDATED_BY = 'employee'
WHERE UPDATED_BY = 'manager';

UPDATE PRODUCT_STATUS_HISTORY
SET CHANGED_BY = 'employee'
WHERE CHANGED_BY = 'manager';
