ALTER TABLE PRODUCT DROP CONSTRAINT CK_PRODUCT_STATUS;

UPDATE PRODUCT
SET STATUS = 'RETIRED'
WHERE STATUS = 'INACTIVE';

ALTER TABLE PRODUCT
  ADD CONSTRAINT CK_PRODUCT_STATUS CHECK (STATUS IN ('ACTIVE', 'RETIRED'));
