server:
  port: 8082
spring:
  application:
    name: customers-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/customers_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8087}
