spring.application.name= security-management-service
#info
info.app.bankName =
info.app.version = 0.0.1
info.app.developer=BLR
info.app.name = SMS Service


server.port=8081

#Database
spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#dialect for spring data jpa
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#health actuator
#health,info,metrics,beans,mappings,loggers,env
management.endpoints.web.exposure.include=*
#health of application should be visible
management.endpoint.health.show-details=always
#enable the access of variable which declared below
management.info.env.enabled=true 
management.endpoint.beans.access=read_only
management.endpoints.web.base-path=/management

logging.level.root = info
logging.level.com.priyansh.example.userservice.controller = debug
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

logging.log4j2.rollingpolicy.max-file-size=20MB
logging.log4j2.rollingpolicy.max-history=7

eureka.client.service-url.defaultzone = http://localhost:8761/eureka
eureka.client.register-with-eureka=true