server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: products-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: ECHO

  flyway:
    schemas: ECHO
    default-schema: ECHO
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8087}

app:
  cors:
    allowed-origins: ${PRODUCT_UI_ORIGINS:http://localhost:8000,http://localhost:8001,http://localhost:8002,http://localhost:8082}