server:
  port: 8083
spring:
  application:
    name: products-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/products_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8087}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

