server:
  port: 8086
spring:
  application:
    name: audit-service
  datasource:
    url: ${DBURL}
    username: ${DBUSER}
    password: ${DBPASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8087}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
