server:
  port: 8086
spring:
  application:
    name: audit-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/audit_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8087}
