server:
  port: 8085
spring:
  application:
    name: transactions-service
  datasource:
    url: ${DBURL}
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8087}
services:
  accounts:
    base-url: ${ACCOUNTS_SERVICE_URL:http://accounts-service}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
